### PR TITLE
*: Format import

### PR DESCRIPTION
**Pull request by Xuanwo**
This PR will format all golang import into the following style

```
import (
  std
  
  3rd

  self
)
```

Also, it will fix `go.mod` not reflect the latest deps.

Signed-off-by: Xuanwo <github@xuanwo.io>

### CODE REVIEW

**Comment by yetone** [comment]
Help with modifications would be greatly appreciated, could you provide a ci to help check for such import order issues?

**Comment by Xuanwo** [comment]
> Help with modifications would be greatly appreciated, could you provide a ci to help check for such import order issues?

Great, I use `goimports` for this. Should I add it in this PR or start a new one?

**Comment by yetone** [comment]
@Xuanwo Thanks! I think you can add this GitHub action to this PR

**Comment by Xuanwo** [comment]
Wired, we already have `.golangci.yaml` to check the `goimports`: https://github.com/bentoml/Yatai/blob/858195003a8efbc6b068a32054b54ac25b562e44/.golangci.yaml#L26-L41

And we have `goimports.sh` and `goimports-check.sh` in `scripts/ci`.

**Comment by yetone** [comment]
@Xuanwo I was wondering why golangci-lint didn't report an error before 🥲

**Comment by Xuanwo** [comment]
Oh, I know what happened.

`golangci-lint` reports many errors at my side:

```shell
:( ./scripts/ci/golint.sh
Running golangci-lint...
WARN [runner] The linter 'scopelint' is deprecated (since v1.39.0) due to: The repository of the linter has been deprecated by the owner.  Replaced by exportloopref.
api-server/services/cluster.go:28: File is not `goimports`-ed with -local github.com/bentoml/yatai (goimports)
        "github.com/bentoml/grafana-operator/api/integreatly/v1alpha1"
api-server/services/yatai_component.go:38: File is not `goimports`-ed with -local github.com/bentoml/yatai (goimports)
        "github.com/bentoml/grafana-operator/api/integreatly/v1alpha1"
api-server/services/cluster_member.go:52:2: ineffectual assignment to err (ineffassign)
        err = nil
        ^
api-server/services/organization_member.go:47:2: ineffectual assignment to err (ineffassign)
        err = nil
        ^
api-server/services/bento.go:233:3: error is not nil (line 231) but it returns nil (nilerr)
                return "", nil
                ^
api-server/services/bento.go:237:3: error is not nil (line 235) but it returns nil (nilerr)
                return "", nil
                ^
api-server/services/bento.go:255:3: error is not nil (line 253) but it returns nil (nilerr)
                return "", nil
                ^
api-server/services/bento.go:259:3: error is not nil (line 257) but it returns nil (nilerr)
                return "", nil
                ^
api-server/services/kube_namespace.go:34:5: error is nil (line 32) but it returns error (nilerr)
                                return
                                ^
api-server/services/model.go:216:3: error is not nil (line 214) but it returns nil (nilerr)
                return "", nil
                ^
api-server/services/model.go:220:3: error is not nil (line 218) but it returns nil (nilerr)
                return "", nil
                ^
api-server/services/model.go:238:3: error is not nil (line 236) but it returns nil (nilerr)
                return "", nil
                ^
api-server/services/model.go:242:3: error is not nil (line 240) but it returns nil (nilerr)
                return "", nil
                ^
common/utils/string_test.go:25:13: SA4025: the integer division '123 / 1024' results in zero (staticcheck)
        isEqual(t, 123/1024, r)
                   ^
api-server/cmd/serve.go:308:9: Function `addCron` should pass the context parameter (contextcheck)
        addCron()
               ^
api-server/main.go:6: File is not `goimports`-ed with -local github.com/bentoml/yatai (goimports)
        grafanav1alpha1 "github.com/bentoml/grafana-operator/api/integreatly/v1alpha1"
api-server/controllers/controllersv1/pod_debug.go:383:18: Function `deleteAgent` should pass the context parameter (contextcheck)
                                o.deleteAgent(agentPod)
                                             ^
api-server/controllers/controllersv1/pod_debug.go:208:14: Function `auth` should pass the context parameter (contextcheck)
        err = o.auth(pod)
                    ^
api-server/controllers/controllersv1/pod_debug.go:218:30: Function `launchPod` should pass the context parameter (contextcheck)
                agentPod, err = o.launchPod(agentPod)
                                           ^
api-server/controllers/controllersv1/pod_debug.go:242:25: Function `launchPod` should pass the context parameter (contextcheck)
                pod, err = o.launchPod(pod)
                                      ^
api-server/controllers/controllersv1/pod_debug.go:245:17: Function `deleteAgent` should pass the context parameter (contextcheck)
                        o.deleteAgent(agentPod)
                                     ^
api-server/controllers/controllersv1/pod_debug.go:251:16: Function `deleteAgent` should pass the context parameter (contextcheck)
                o.deleteAgent(agentPod)
                             ^
api-server/controllers/controllersv1/terminal.go:242:14: Function `Run` should pass the context parameter (contextcheck)
        return o.Run()
                    ^
api-server/controllers/controllersv1/log.go:190:19: Error return value of `encoding/json.Marshal` is not checked: unsafe type `interface{}` found (errchkjson)
                                        msgStr, _ := json.Marshal(&msg)
                                                     ^
api-server/controllers/controllersv1/log.go:233:22: Error return value of `encoding/json.Marshal` is not checked: unsafe type `interface{}` found (errchkjson)
                                                                msgStr, _ := json.Marshal(&msg)
                                                                             ^
./scripts/ci/golint.sh  6.20s user 1.03s system 644% cpu 1.121 total
```

But no error in CI:

```shell
docker run -u root --privileged --rm --net=host -v "/pkg/mod":/go/pkg/mod -v /usr/share/zoneinfo/Etc/UTC:/etc/localtime:ro -v /home/runner/work/Yatai/Yatai:/code -w /code quay.io/bentoml/yatai-builder:1.0 ./scripts/ci/golint.sh
Running golangci-lint...
[PASS] golangci-lint passed!
```

Something is wrong here.

**Comment by yetone** [comment]
@Xuanwo Thanks for the feedback, I'll follow up on this issue

**Comment by Xuanwo** [comment]
I remeber that mounting workspace into container directly is buggy in github actions. 

I used https://github.com/addnab/docker-run-action to workaround that: see https://github.com/pengx17/logseq-publish/pull/5 for more information

**Comment by yetone** [comment]
@Xuanwo great! I will fix this.

**Comment by yetone** [comment]
@Xuanwo In this [PR](https://github.com/bentoml/Yatai/pull/143) I fixed the problem with the golangci-lint github action, you can rebase the main branch upstream

**Comment by yetone** [comment]
@Xuanwo You may need to rebase upstream again in order to run the github action correctly 😅

**Comment by Xuanwo** [comment]
> @Xuanwo You may need to rebase upstream again in order to run the github action correctly sweat_smile

Done, PTAL.

**Comment by yetone** [comment]
LGTM!

**Pull request merged**
